### ISSUE TITLE
Unable to clone repository on Windows due to invalid folder name

### ISSUE THREAD

**Issue by LeifuChen** [iuliana/personal-records#1]
Unable to clone the following dictionaries on Windows because 'con' is a reserved word. 
13-pr-webflow-subflow-solution\src\test\java\con
14-pr-web-security-practice\src\test\java\con
14-pr-web-security-solution\src\test\java\con

I also think 'con' is typo here. It should be replaced by 'com', right?

**Comment by iuliana** [comment]
Hi Chen,

I will take care of it. Thank you for the feedback!

**Comment by iuliana** [comment]
Issue is now fixed.
